# This file relates to internal XMOS infrastructure and should be ignored by users
---
an_number: an01009
an_number_upper: AN01009
project: '{{an_number}}'
title: '{{an_number_upper}}: Optimising USB Audio for stereo output, battery powered devices'
version: 2.1.0

documentation:
  exclude_patterns_path: doc/exclude-patterns.inc
  root_doc: doc/rst/an01009.rst
  linkcheck_ignore_regex: [".*"]
  cognidox_part_number: XM-006863-AN
  pdfs:
    doc/rst/an01009.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{an_number}}_v{{version}}'
      pdf_short: yes
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{an_number}}_v{{version}}_readme'
      pdf_short: yes

software:
  cognidox_part_number: XM-015176-SM
